import {test} from 'node:test';
import assert from 'node:assert/strict';
import {walls,wallRects,overlaps,initialFurniture,migrateLayout,clone,LAYOUT_REVISION,columns,wallJoints,WALL_THICKNESS,inside,doors,curtains} from '../dist/model.js';
test('bedroom B balcony boundary is closed at floor level and balcony door starts beyond bedroom',()=>{for(let z=3.8;z<5.77;z+=.01)assert(wallRects().some(w=>overlaps({x:6.57,z,w:.015,d:.015,rot:0},w)),String(z));const door=walls.find(w=>w.id==='balcony-door-wall');assert(door.a[1]+door.opening[0]>=5.78);const window=walls.find(w=>w.id==='window-B');assert.equal(window.opening[1],1.06);assert(window.opening[2]>0);});
test('master glazing follows 163 cm dimension and bath glazing is beside the shower',()=>{const master=walls.find(w=>w.id==='window-master');assert.equal(master.opening[1],1.63);assert.equal(master.a[0]+master.opening[0],6.449999999999999);const bath=walls.find(w=>w.id==='window-bathB');const shower=initialFurniture.find(f=>f.id==='showerB');const center=bath.a[1]+bath.opening[0]+bath.opening[1]/2;assert(Math.abs(center-shower.z)<shower.d/2);assert.equal(walls.filter(w=>w.id?.startsWith('window-')).length,5);});
test('master bedroom upper-right corner follows the plan without an interior column',()=>{assert.equal(columns.some(c=>c.x>6.57&&c.z<2.7),false);});
test('outside columns and every highlighted wall junction follow one continuous footprint',()=>{const north=columns.find(c=>c.id==='living-north-column'),entry=columns.find(c=>c.id==='entry-column'),balcony=columns.find(c=>c.id==='balcony-south-column'),near=(a,b)=>assert(Math.abs(a-b)<1e-9);near(north.w-WALL_THICKNESS,.4);near(north.d-WALL_THICKNESS,.49);near(north.x-north.w/2,-WALL_THICKNESS/2);near(north.z-north.d/2,-WALL_THICKNESS/2);assert.deepEqual([entry.w,entry.d],[.80,.84]);assert.deepEqual([balcony.w,balcony.d],[.85,.85]);near(balcony.x-balcony.w/2,8.1);near(balcony.x+balcony.w/2,8.95);near(balcony.z+balcony.d/2,7.31);for(const point of[[0,0],[8.4,0],[2.82,2.72],[5.18,2.72],[6.57,2.7],[8.4,2.7],[1.52,4.75],[3.08,4.75],[3.83,5.78],[6.57,5.78],[1.85,8.53],[-.45,8.53]]){const joint=wallJoints.find(j=>j.x===point[0]&&j.z===point[1]);assert(joint,point.join(','));assert.equal(joint.w,WALL_THICKNESS);assert.equal(joint.d,WALL_THICKNESS);}});
test('work-balcony lower-right column projects outside and closes the revised shell',()=>{const column=columns.find(c=>c.id==='balcony-south-column'),railing=walls.find(w=>w.id==='balcony-railing');assert.deepEqual(railing.b,[8.4,6.46]);assert(inside(column.x,column.z));assert(wallRects().some(w=>w.id===column.id));assert.equal(walls.some(w=>w.a[0]===8.3&&w.a[1]===7.25),false);});
test('the entry end wall runs 160 cm clear from the bath-A step and meets the column without a notch',async()=>{const {roomAt}=await import('../dist/geometry.js');const block=wallRects().find(w=>w.id==='bath-A-block'),end=walls.find(w=>w.a[0]===1.85&&w.b[0]===1.85&&w.b[1]===8.53),south=walls.find(w=>w.a[1]===8.53&&w.b[1]===8.53),near=(a,b)=>assert(Math.abs(a-b)<1e-9);near(south.a[1]-WALL_THICKNESS/2-end.a[1],1.6);near(block.z+block.d/2,end.a[1]);assert(block.x+block.w/2>1.85-WALL_THICKNESS/2,'column and end wall overlap');for(let z=6.2;z<8.5;z+=.01)assert(wallRects().some(w=>overlaps({x:1.85,z,w:.015,d:.015,rot:0},w)),String(z));assert.equal(roomAt(1.6,7.05),'玄關');assert.equal(roomAt(2.4,7.05),'衛浴 A');assert.equal(wallRects().some(w=>w.id==='bath-A-step'),false);});
test('entry bridge shares the column face and bath-A door starts at the wall edge',()=>{const column=columns.find(c=>c.id==='entry-column'),bridge=walls.find(w=>w.a[0]===-.45&&w.b[0]===0),bathDoor=doors.find(d=>d.name==='衛浴 A 房門'),near=(a,b)=>assert(Math.abs(a-b)<1e-9);near(bridge.a[1]-WALL_THICKNESS/2,column.z-column.d/2);assert.deepEqual([bathDoor.x,bathDoor.z],[3.08,4.75]);});
test('living curtain starts at the north column face',()=>{const column=columns.find(c=>c.id==='living-north-column'),curtain=curtains.find(c=>c.id==='curtain-0');assert(Math.abs(curtain.x-curtain.w/2-(column.x+column.w/2))<1e-9);});
test('bathroom defaults touch their walls and both sinks share the remaining width',()=>{const get=id=>initialFurniture.find(f=>f.id===id),sinkA=get('bathSink1'),sinkB=get('bathSink2'),toiletA=get('toilet1'),toiletB=get('toilet2'),near=(a,b)=>assert(Math.abs(a-b)<1e-9);assert.equal(sinkA.w,sinkB.w);near(sinkA.x-sinkA.d/2,1.52+WALL_THICKNESS/2);near(sinkB.x+sinkB.d/2,8.85-WALL_THICKNESS/2);near(toiletA.x-toiletA.d/2,1.52+WALL_THICKNESS/2);near(toiletB.z+toiletB.d/2,4.4-WALL_THICKNESS/2);assert.equal(toiletA.z,5.92);});
test('kitchen defaults fill the plan run without crossing the walls',()=>{const kitchen=initialFurniture.find(f=>f.id==='kitchen');assert.equal(kitchen.w,2.08);assert.equal(kitchen.d,.58);assert(Math.abs(kitchen.x+kitchen.w/2-(6.57-WALL_THICKNESS/2))<1e-9);assert(Math.abs(kitchen.z+kitchen.d/2-(7.25-WALL_THICKNESS/2))<1e-9);});
test('layout migration corrects fixtures, adds wet areas once and preserves unrelated custom edits',()=>{const old=clone(initialFurniture).filter(f=>f.type!=='shower');old.find(f=>f.id==='sofa').x=1.23;old.find(f=>f.id==='kitchen').rot=90;const result=migrateLayout(old,0);assert.equal(result.find(f=>f.id==='sofa').x,1.23);assert.equal(result.find(f=>f.id==='kitchen').rot,180);assert.equal(result.filter(f=>f.type==='shower').length,2);const custom=clone(result);custom.find(f=>f.id==='kitchen').x=5;assert.equal(migrateLayout(custom,LAYOUT_REVISION).find(f=>f.id==='kitchen').x,5);assert.equal(migrateLayout(result,0).filter(f=>f.type==='shower').length,2);});
test('the enlarged north column only moves the untouched default TV cabinet',()=>{const old=clone(initialFurniture),tv=old.find(f=>f.id==='tv');tv.z=1.3;assert.equal(migrateLayout(old,6).find(f=>f.id==='tv').z,1.57);tv.x=.5;assert.equal(migrateLayout(old,6).find(f=>f.id==='tv').z,1.3);});
test('revision nine migrates only untouched bathroom defaults',()=>{const old=clone(initialFurniture),values={bathSink1:[1.77,5.17,.55,.43,90],toilet1:[1.91,5.84,.4,.67,90],bathSink2:[8.49,3.12,.52,.42,-90],toilet2:[7.02,3.87,.4,.67,180]};for(const [id,[x,z,w,d,rot]]of Object.entries(values))Object.assign(old.find(f=>f.id===id),{x,z,w,d,rot});const custom=clone(old);custom.find(f=>f.id==='bathSink1').x=1.7;const migrated=migrateLayout(old,8),preserved=migrateLayout(custom,8);for(const id of Object.keys(values))assert.deepEqual(migrated.find(f=>f.id===id),initialFurniture.find(f=>f.id===id));assert.equal(preserved.find(f=>f.id==='bathSink1').x,1.7);});
test('revision ten migrates untouched kitchen and Bath-A toilet defaults',()=>{const old=clone(initialFurniture);Object.assign(old.find(f=>f.id==='kitchen'),{x:5.43,z:6.87,w:2,d:.62,rot:180});Object.assign(old.find(f=>f.id==='toilet1'),{x:1.795,z:5.84,w:.4,d:.67,rot:90});const custom=clone(old);custom.find(f=>f.id==='kitchen').x=5.2;custom.find(f=>f.id==='toilet1').z=5.95;const migrated=migrateLayout(old,9),preserved=migrateLayout(custom,9);assert.deepEqual(migrated.find(f=>f.id==='kitchen'),initialFurniture.find(f=>f.id==='kitchen'));assert.deepEqual(migrated.find(f=>f.id==='toilet1'),initialFurniture.find(f=>f.id==='toilet1'));assert.equal(preserved.find(f=>f.id==='kitchen').x,5.2);assert.equal(preserved.find(f=>f.id==='toilet1').z,5.95);});

test('the open passage between the master corridor and bedroom belongs to the master bedroom',async()=>{
 const {roomAt}=await import('../dist/geometry.js');
 for(const x of[5.2,5.9,6.5])for(const z of[2.71,2.74,2.77])assert.equal(roomAt(x,z),'主臥室');
});

test('rooms follow the dimensions printed on A7',()=>{
 const T=WALL_THICKNESS,near=(a,b,label,tolerance=.011)=>assert(Math.abs(a-b)<tolerance,`${label}: ${a.toFixed(3)} vs ${b}`),wall=(ax,az,bx,bz)=>walls.find(w=>w.a[0]===ax&&w.a[1]===az&&w.b[0]===bx&&w.b[1]===bz);
 // Master bedroom: 121 + 163 + 27 cm across the north wall, 169 cm along the south wall east of bath B.
 // The two chains put the east wall at 8.41 and 8.38; it sits between them.
 near(8.4-5.18-T,3.11,'master width',.021);near(8.4-6.57-T,1.69,'master south wall',.021);
 // Bedroom A 261 cm deep, corridor 90 cm to bedroom B's north wall.
 near(2.72-T/2-T/2,2.61-.01,'bedroom A depth');near(3.72-2.72-T,.88,'corridor');
 // Bath A 168 cm outside to outside; bath B door 74 cm, 12 cm below the master's south wall face.
 near(3.08-1.52+T,1.68,'bath A outside');
 const bathB=wall(6.57,2.7,6.57,4.4);near(bathB.opening[1],.74,'bath B door');near(bathB.a[1]+bathB.opening[0]-(2.7+T/2),.12,'bath B door offset');
 // Bedroom B window 80 cm below its north wall face; balcony block 88 cm from the bedroom-B wall face.
 const windowB=walls.find(w=>w.id==='window-B');near(windowB.a[1]+windowB.opening[0]-(3.72+T/2),.8,'bedroom B window');
 const block=wallRects().find(w=>w.id==='balcony-north-block');near(block.x-block.w/2-(6.57+T/2),.88,'balcony block');
});
