import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import {SpaceScene} from '../dist/scene.js';
import {doors,initialFurniture,wallRects} from '../dist/model.js';
function setup(mode='walk'){
 globalThis.window=new EventTarget;globalThis.document=new EventTarget;document.querySelector=()=>null;
 const canvas=new EventTarget;canvas.setPointerCapture=()=>{};canvas.hasPointerCapture=()=>false;
 const s=Object.create(SpaceScene.prototype);Object.assign(s,{mode,renderer:{domElement:canvas,render(){}},host:{clientHeight:600},camera:new T.PerspectiveCamera(70,1,.1,100),topCamera:new T.OrthographicCamera(-6,6,6,-6),keys:new Set,actions:new Map,items:[],walkYaw:0,walkPitch:0,eye:1.6,viewStates:{},controls:{enabled:false,enableDamping:true,target:new T.Vector3,update(){}},pick:()=>null,ground:e=>new T.Vector3(e.clientX/100,0,e.clientY/100),onSelect(){},onDrag(){},onDragEnd(){},onOperate(){},setCutaway(){},updateGrid(){},collisionWalls:wallRects(),clock:{getDelta:()=>.04},scene:new T.Scene});s.bind();
 const emit=(type,props={})=>{const e=new Event(type,{cancelable:true});Object.assign(e,{button:0,buttons:1,pointerId:1,pointerType:'mouse',clientX:100,clientY:100,...props});canvas.dispatchEvent(e);};return{s,emit};
}
test('grab direction follows drag and releases outside / lost capture never leave a ghost drag',()=>{const{s,emit}=setup();emit('pointerdown');emit('pointermove',{clientX:140,clientY:120});assert(s.walkYaw>0);assert(s.walkPitch>0);window.dispatchEvent(new Event('pointerup'));const yaw=s.walkYaw;emit('pointermove',{clientX:190,buttons:0});assert.equal(s.walkYaw,yaw);emit('pointerdown');emit('lostpointercapture');emit('pointermove',{clientX:200});assert.equal(s.walkYaw,yaw);});
test('single click selects and operates exactly once; dragging never toggles an object',()=>{const{s,emit}=setup();s.actions.set('door',{});s.pick=()=>({kind:'action',id:'door'});let count=0,picked=null;s.onSelect=id=>picked=id;s.onOperate=()=>count++;emit('pointerdown');emit('pointerup');assert.equal(picked,'door');assert.equal(count,1);emit('pointerdown');emit('pointermove',{clientX:140});emit('pointerup',{clientX:140});assert.equal(count,1);});
test('top view pans blank space and dragging furniture ends once',()=>{const{s,emit}=setup('top');emit('pointerdown');emit('pointermove',{clientX:150,clientY:130});emit('pointerup',{clientX:150,clientY:130});assert.equal(s.topCamera.position.x,-1);assert.equal(s.topCamera.position.z,-.6);s.pick=()=>({kind:'furniture',id:'a'});s.items=[{id:'a',x:1,z:1}];let moves=0,ends=0;s.onDrag=()=>moves++;s.onDragEnd=()=>ends++;emit('pointerdown');emit('pointermove',{clientX:150});emit('pointerup',{clientX:150});assert.equal(moves,1);assert.equal(ends,1);});
test('placement mode sends a blank-plan click to the requested location and Escape cancels it',()=>{const{s,emit}=setup('top');let point=null,cancelled=0;s.host.classList={add(){},remove(){}};s.onPlace=(x,z)=>point=[x,z];s.onCancelPlacement=()=>cancelled++;s.startPlacement();emit('pointerdown',{clientX:230,clientY:410});emit('pointerup',{clientX:230,clientY:410});assert.deepEqual(point,[2.3,4.1]);s.startPlacement();const e=new Event('keydown',{cancelable:true});Object.assign(e,{code:'Escape'});window.dispatchEvent(e);assert.equal(s.placing,false);assert.equal(cancelled,1);});
test('walk wheel FOV is bounded and all three modes retain positions',()=>{const{s,emit}=setup('orbit');s.camera.position.set(8,9,10);s.camera.fov=43;s.setMode('walk');assert.equal(s.camera.fov,70);s.camera.position.set(2,1.6,3);s.walkYaw=.6;emit('wheel',{deltaY:9999});assert.equal(s.camera.fov,95);s.setMode('top');s.topCamera.position.set(5,25,6);s.topCamera.zoom=2;s.setMode('orbit');assert.deepEqual(s.camera.position.toArray(),[8,9,10]);assert.equal(s.camera.fov,43);s.setMode('walk');assert.deepEqual(s.camera.position.toArray(),[2,1.6,3]);assert.equal(s.walkYaw,.6);assert.equal(s.camera.fov,95);s.setMode('top');assert.equal(s.topCamera.zoom,2);assert.deepEqual(s.topCamera.position.toArray(),[5,25,6]);});
test('up plus left turns while advancing; low dining furniture permits passage while tall cabinets and walls remain solid',()=>{const{s}=setup();s.camera.position.set(1,1.6,3);s.items=initialFurniture;s.keys.add('ArrowUp');s.keys.add('ArrowLeft');s.frame();assert(s.walkYaw>0);assert(s.camera.position.z<3);assert(s.canWalk(1.96,3.55));assert(!s.canWalk(5.58,1.27));assert(!s.canWalk(0,3));s.avoidFurniture=true;assert(s.canWalk(1.96,3.55));assert(!s.canWalk(5.58,1.27));});
test('room door leaves swing into rooms instead of circulation',()=>{const endpoint=d=>[d.x+Math.cos(d.angle+d.swing*Math.PI/2)*d.width,d.z-Math.sin(d.angle+d.swing*Math.PI/2)*d.width];assert(endpoint(doors[0])[0]>doors[0].x);assert(endpoint(doors[1])[1]<doors[1].z);for(const i of[2,3,4,5])assert(endpoint(doors[i])[0]>doors[i].x);assert(endpoint(doors[6])[0]<doors[6].x);});
test('selected furniture consumes arrow keys for nudges; Escape restores navigation',()=>{const{s}=setup();s.items=[{id:'chair'}];s.selected='chair';s.onSelect=id=>s.selected=id;const calls=[];s.onNudge=(...args)=>calls.push(args);const key=(code,shiftKey=false)=>{const e=new Event('keydown',{cancelable:true});Object.assign(e,{code,shiftKey});window.dispatchEvent(e);};key('ArrowRight',true);assert.deepEqual(calls,[['chair','ArrowRight',true]]);assert.equal(s.keys.size,0);key('Escape');assert.equal(s.selected,null);key('ArrowUp');assert(s.keys.has('ArrowUp'));});

test('automatic walking completes around furniture without entering an obstacle',async()=>{
 const {rooms}=await import('../dist/model.js');const {fixedDoorLimit,roomAt}=await import('../dist/spatial.js');
 const{s}=setup();s.items=initialFurniture;s.openStates={};s.camera.position.set(.75,1.6,7.7);
 for(const d of doors){d.maxAngle=fixedDoorLimit(d);s.actions.set(d.id,{type:'door',def:d,amount:0,pivot:new T.Group});}
 s.onNavigationNotice=message=>assert.fail(message);for(const room of rooms){assert(s.startTour(room),room.name);let steps=0;while(s.route.length&&steps++<2000){s.frame();assert(s.canWalk(s.camera.position.x,s.camera.position.z),room.name);}assert(steps<2000);assert.equal(roomAt(s.camera.position.x,s.camera.position.z),roomAt(room.x,room.z),room.name+JSON.stringify(s.camera.position.toArray()));}
});
