import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {SpaceScene} from '../dist/scene.js';
import {initialFurniture,minimums,wallRects} from '../dist/model.js';
function fixture(){const s=Object.create(SpaceScene.prototype);s.m=Object.fromEntries(['wood','fabric','white','accent','dark','metal','stone','glass','leaf'].map(k=>[k,new THREE.MeshStandardMaterial()]));s.actions=new Map;s.collisionWalls=wallRects();s.items=[];return s;}
test('every furniture type generates finite geometry at initial and minimum dimensions',()=>{const s=fixture();for(const f of initialFurniture)for(const dims of[[f.w,f.d,f.h],minimums[f.type]]){const g=new THREE.Group;s.makeFurniture(g,{...f,w:dims[0],d:dims[1],h:dims[2]});assert(g.children.length>0);g.traverse(o=>{if(o.geometry){const a=o.geometry.attributes.position.array;for(const n of a)assert(Number.isFinite(n),f.name);o.geometry.computeBoundingBox();assert(!o.geometry.boundingBox.isEmpty(),f.name);}});}});
test('cabinet resized parts and animation pivots share updated dimensions',()=>{const s=fixture(),g=new THREE.Group;const f={...initialFurniture.find(f=>f.type==='wardrobe'),doorStyle:'double',w:1.8,d:.7,h:2.5};s.makeFurniture(g,f);const a=s.actions.get(f.id);assert.equal(a.pivots.length,2);assert.equal(a.base,.35);assert.equal(a.item.h,2.5);assert.equal(a.pivots[0].position.y,1.25);});
test('walking collides with furniture and extended drawers',()=>{const s=fixture(),f={...initialFurniture.find(f=>f.type==='drawer'),x:1,z:3,w:.5,d:.5,h:.5};s.items=[f];s.avoidFurniture=true;s.actions.set(f.id,{type:'cabdrawer',item:f,amount:1,travel:.4});assert(!s.canWalk(1,3));assert(!s.canWalk(1,3.5));assert(s.canWalk(.6,3.7));});

test('left, right and paired cabinet meshes use their selected hinges',()=>{const s=fixture();for(const doorStyle of ['left','right','double']){const f={...initialFurniture.find(f=>f.type==='wardrobe'),doorStyle},g=new THREE.Group;s.makeFurniture(g,f);const a=s.actions.get(f.id);assert.equal(a.pivots.length,doorStyle==='double'?2:1);for(const p of a.pivots){assert.equal(Math.sign(p.position.x),p.userData.swing);p.rotation.y=p.userData.swing*Math.PI/2;p.updateMatrixWorld(true);const slab=p.children[0],center=slab.getWorldPosition(new THREE.Vector3);assert(center.z>f.d/2);}}});
