import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {SpaceScene,floorBoardRects} from '../dist/scene.js';
import {initialFurniture,minimums,wallRects,overlaps} from '../dist/model.js';
function fixture(){const s=Object.create(SpaceScene.prototype);s.m=Object.fromEntries(['wood','fabric','white','accent','dark','metal','stone','glass','leaf'].map(k=>[k,new THREE.MeshStandardMaterial()]));s.actions=new Map;s.collisionWalls=wallRects();s.items=[];s.invalidHelpers=new Map;s.invalidMarkers=new Map;s.foregroundDraft=null;return s;}
test('every furniture type generates finite geometry at initial and minimum dimensions',()=>{const s=fixture();for(const f of initialFurniture)for(const dims of[[f.w,f.d,f.h],minimums[f.type]]){const g=new THREE.Group;s.makeFurniture(g,{...f,w:dims[0],d:dims[1],h:dims[2]});assert(g.children.length>0);g.traverse(o=>{if(o.geometry){const a=o.geometry.attributes.position.array;for(const n of a)assert(Number.isFinite(n),f.name);o.geometry.computeBoundingBox();assert(!o.geometry.boundingBox.isEmpty(),f.name);}});}});
test('cabinet resized parts and animation pivots share updated dimensions',()=>{const s=fixture(),g=new THREE.Group;const f={...initialFurniture.find(f=>f.type==='wardrobe'),doorStyle:'double',w:1.8,d:.7,h:2.5};s.makeFurniture(g,f);const a=s.actions.get(f.id);assert.equal(a.pivots.length,2);assert.equal(a.base,.35);assert.equal(a.item.h,2.5);assert.equal(a.pivots[0].position.y,1.25);});
test('floor boards stay clear of wall thickness at the exposed master edge',()=>{const boards=floorBoardRects(),walls=wallRects();assert(boards.length>0);for(const board of boards)for(const wall of walls)assert.equal(overlaps(board,wall),false,`${board.x},${board.z} crosses ${wall.x},${wall.z}`);});
test('both shower enclosures expose a hinged glass-door action',()=>{const s=fixture();for(const f of initialFurniture.filter(f=>f.type==='shower')){const g=new THREE.Group;s.makeFurniture(g,f);const action=s.actions.get(f.id);assert.equal(action.type,'shower');assert(action.pivot.children.length>=5);assert.equal(action.item,f);}});
test('walking collides with furniture and extended drawers',()=>{const s=fixture(),f={...initialFurniture.find(f=>f.type==='drawer'),x:1,z:3,w:.5,d:.5,h:.5};s.items=[f];s.avoidFurniture=true;s.actions.set(f.id,{type:'cabdrawer',item:f,amount:1,travel:.4});assert(!s.canWalk(1,3));assert(!s.canWalk(1,3.5));assert(s.canWalk(.6,3.7));});
test('draft furniture has a strong red editor marker and is hidden outside top view',()=>{const s=fixture(),f={...initialFurniture[0],draft:true},g=new THREE.Group;g.add(new THREE.Mesh(new THREE.BoxGeometry(f.w,f.h,f.d)));s.scene=new THREE.Scene;s.groups=new Map([[f.id,g]]);s.items=[f];s.selected=null;s.selection=null;s.mode='top';s.scene.add(g);s.refreshValidity();const marker=s.invalidMarkers.get(f.id);assert.equal(g.visible,true);assert.equal(s.invalidHelpers.get(f.id).visible,true);assert.equal(marker.visible,true);assert.equal(marker.children.length,5);assert(marker.children[0].material.opacity>=.3);s.setForegroundDraft(f.id);assert(g.position.y>0);assert(marker.position.y>g.position.y+f.h);s.mode='orbit';s.refreshValidity();assert.equal(g.visible,false);assert.equal(marker.visible,false);assert.equal(g.position.y,0);f.draft=false;s.refreshValidity();assert.equal(g.visible,true);assert.equal(s.invalidHelpers.has(f.id),false);assert.equal(s.invalidMarkers.has(f.id),false);});

test('top picking prioritizes the most recently moved interfering furniture',()=>{globalThis.document={pointerLockElement:null};const s=fixture(),large=new THREE.Group,small=new THREE.Group,largeMesh=new THREE.Mesh,smallMesh=new THREE.Mesh;large.userData.furniture='large';small.userData.furniture='small';large.add(largeMesh);small.add(smallMesh);Object.assign(s,{mode:'top',foregroundDraft:'small',host:{getBoundingClientRect:()=>({left:0,top:0,width:100,height:100})},renderer:{domElement:{}},pointer:new THREE.Vector2,topCamera:new THREE.OrthographicCamera,furniture:new THREE.Group,building:new THREE.Group});s.ray={setFromCamera(){},intersectObjects:()=>[{object:largeMesh},{object:smallMesh}]};assert.deepEqual(s.pick({clientX:50,clientY:50}),{kind:'furniture',id:'small'});});
test('left, right and paired cabinet meshes use their selected hinges',()=>{const s=fixture();for(const doorStyle of ['left','right','double']){const f={...initialFurniture.find(f=>f.type==='wardrobe'),doorStyle},g=new THREE.Group;s.makeFurniture(g,f);const a=s.actions.get(f.id);assert.equal(a.pivots.length,doorStyle==='double'?2:1);for(const p of a.pivots){assert.equal(Math.sign(p.position.x),p.userData.swing);p.rotation.y=p.userData.swing*Math.PI/2;p.updateMatrixWorld(true);const slab=p.children[0],center=slab.getWorldPosition(new THREE.Vector3);assert(center.z>f.d/2);}}});
